# Generated by Django 4.0 on 2021-12-21 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0002_remove_category_city_property_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='state', to='Property.state'),
            preserve_default=False,
        ),
    ]
